spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/delivery?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false

server:
  port: 7000
  tomcat:
    uri-encoding: UTF-8


management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 17000
    servlet:
      context-path: /
    tomcat:
      uri-encoding: UTF-8
    compression:
      enabled: true
      mimeTypes: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.delivery.mapper: DEBUG

