spring:
  application:
    name: delivery-platform-backend
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/delivery?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false

server:
  port: 7000
  tomcat:
    uri-encoding: UTF-8


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    jmx:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  metrics:
    export:
      datadog:
        application-key: ${spring.application.name}
  server:
    port: 17000


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.delivery.mapper: DEBUG

